Fashion/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url('^admin/', admin.site.urls),
    url('', include('fashionapp.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fashionapp/urls.py
from django.urls import path
from . import views

app_name = 'fashionapp'

urlpatterns =[
    path('', views.index, name='index'),
    path('(?P<clothe_id>[0-9]+)/', views.details, name='detail'),
    path('create_clothe/', views.create_clothe, name='create_clothe'),
    path('(?P<clothe_id>[0-9]+)/delete_clothe',views.delete_clothe, name='delete_clothe'),
    path('register/',views.register,name = 'register'),
    path('login/', views.login_user, name ='login_user'),
    path('logout/', views.logout_user, name = 'logout_user'),



]

fashionapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class Clothe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    material = models.CharField(max_length=15)
    type = models.CharField(max_length=20)
    cover = models.ImageField()


    def __str__(self):
        return self.material

fashionapp/forms.py
from django import forms
from . models import Clothe,User


class ClotheForm(forms.ModelForm):
    class Meta:
        model = Clothe
        fields = ('material','type','cover',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username','email','password')

fashionapp/views.py
from django.shortcuts import render,get_object_or_404, redirect
from . models import Clothe
from . forms import ClotheForm,UserForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    clothes =Clothe.objects.all()
    return render(request, 'fashionapp/index.html', {'clothes':clothes})


def details(request,Clothe_id):
        clothe = get_object_or_404(Clothe, pk= Clothe_id)
        return render(request,'fashionapp/detail.html',{'Clothe': clothe})



@login_required(login_url='fashionapp:login_user')
def create_clothe(request):
    form = ClotheForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        clothe = form.save(commit=False)
        clothe.cover = request.FILES['cover']
        clothe.user = request.user
        clothe.save()
        return redirect('fashionapp:index')
    form = ClotheForm()
    return render(request, 'fashionapp/create_clothe.html', {'form':form})


def delete_clothe(request, clothe_id):
    clothe= Clothe.objects.get(pk=clothe_id)
    clothe.delete()
    return redirect('fashionapp:index')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form . cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username = username,password=password)
        if user is not None:
            if user. is_active:
                login(request,user)
                clothes = Clothe.objects.filter(user=request.user)
            return render( request,'fashionapp/index.html',{'clothes':clothes})
    return render(request,'fashionapp/register.html',{'form':form})



def login_user(request):
    if request .method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('fashionapp:index')
    return render(request, 'fashionapp/login.html')


def logout_user(request):
    logout(request)
    return redirect('fashionapp:login_user')

fashionapp/templates/fashionapp/base.html
<!
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    </head>

<body>

<nav class="navbar navbar-inverse">

    <div class="container-fluid">



        <!-- Header -->

        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

            </button>

            <a class="navbar-brand" href="">Wears</a>

        </div>



        <!-- Items -->

        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">

                <li <a href="index.php"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Home</a></li>



            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="">

                <div class="form-group">

                    <input type="text" class="form-control" name="q" value="">

                </div>

                <button type="submit" class="btn btn-default">Search</button>

            </form>

            <ul class="nav navbar-nav navbar-right">

                <li>

                    <a href="{% url 'fashionapp:create_clothe' %}">

                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Clothe

                    </a>

                </li>

                {%if user.is_authenticated%}
                <li>

                    <a href="{% url 'fashionapp:logout_user' %}">

                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; logout

                    </a>
                </li>

                {% else %}

                <li>

                    <a href="{% url 'fashionapp:login_user' %}">

                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; login

                    </a>

                </li>
                {%endif%}




            </ul>

        </div>



    </div>

</nav>

{% block content %}
{% endblock %}

</body>

</html>

fashionapp/templates/fashionapp/create_clothe.html
{% extends 'fashionapp/base.html' %}
{%load crispy_forms_tags%}
{% block content %}
    <div class="row">
         <div class="col-sm-4">
             <div class="panel panel-default">
                 <div class="panel-heading">
                     <h3 class="text-primary">Add Clothe</h3>
                 </div>
                 <div class="panel-body">
                     <form method="post" action="" enctype="multipart/form-data">
                     {% csrf_token %}
                         {{form|crispy}}

                     <div class ="form-group">
                         <button type="submit" class="btn btn-success">submit</button>
                     </div>
                     </form>
                 </div>
             </div>
         </div>
    </div>
{% endblock %}

fashionapp/templates/fashionapp/detail.html
{% extends 'fashionapp/base.html' %}
{% block content %}
<div class="container-fluid">
   <div class="row">
       <div class="col-sm-3">
           <div class ="thumbnail">
                <img src="{{clothe.cover.url}}" class = "img img- thumbnail img img-responsive">
                   <div class = "caption">
                   <h4>{{ clothe.material }}</h4>
                   <h5>{{ clothe.type }}</h5>
               </div>
           </div>
       </div>
       <div class="col-sm-9">
           <ul class="nav nav-pills">
               <li role="presentation" class="active"><a href="">Clothe</a></li>
               <li role="presentation"><a href="{% url 'fashionapp:create_clothe' %}" >Add Clothe </a></li>
       </ul>
           <div class="panel panel_default">
               <div class="panel_heading">
                   <div class="panel-body">
                       {% if message %}
                       <p class="text-success">{{ 'message' }}</p>
                       {% endif %}
               </div>
               <div>
                   <table class="table">
                       <thead>
                       <tr>
                           <th>Name</th>
                           <th>Favorite</th>
                           <th>Action</th>
                       </tr>
                       </thead>
                       {% if clothe.clothe_set %}
                          {% for clothe in clothe.clothe_set.all %}
                          <tr>
                          <td>{{ clothe.clothe }}</td>
                              <td>
                               <a href="" >
                                   <span class="glyphicon glyphicon-star"></span>
                              </a>

                              <td>
                              <a href="{% url 'fashionapp:delete_Clothe' clothe.id %}">
                                  <button type="button" class="btn btn-danger btn-xs">
                                      <span class="glyphicon glyphicon-trash"></span> Delete
                                  </button>
                                </a>
                          </td>
                          </td>
                          </tr>
                            {% endfor %}
                   {% endif %}
                   </table>
               </div>

           </div>


       </div>


  </div>
   </div>

 </div>
{% endblock %}

fashionapp/templates/fashionapp/index.html
{% extends 'fashionapp/base.html' %}
{% block content %}
<div class="container-fluid">
   <div class="row">
        <h3 class="text-center text-primary">
            {{ request.user.username }}'s Clothes
            <hr>
        </h3>
        {% if clothes %}
        {% for clothe in clothes %}

        <div class="col-sm-3">
            <div class="thumbnail">
                <a href="{% url 'fashionapp:index' %}">
                <img src="{{ clothe.cover.url }}" class="img img-thumbnail" style="height:150px;width:150px;">
                </a>
                    <div class="caption">
                    <h4>{{clothe.material}}</h4>
                    <h5>{{clothe.type}}</h5>
                        <form method = "post" action="{%url 'fashionapp:delete_clothe' clothe.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="clothe_id" value="{{ clothe.id }}">
                        <a href = "{% url 'fashionapp:delete_clothe' clothe.id %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>

                        </form>
                </div>
            </div>
        </div>
        {% endfor %}
       {% endif %}
    </div>
</div>

{% endblock %}

fashionapp/templates/fashionapp/login.html
{% extends 'fashionapp/base.html' %}
{% block content %}
   <div class="container-fluid">
       <div class="row">
           <div class="col-md-4">
           <div class="panel panel-primary">
               <div class="panel-heading">
                   <h3> login</h3>
               </div>
               <div class="panel-body">
                   <form class="form-horizontal" action="" method="post">
                       {% csrf_token %}
                       <div class="form-group">
                           <label class="control-label">username</label>
                           <input type="text" class="form-control" name="username">
                       </div>

                       <div class="form-group">
                           <label class="control-label">password</label>
                           <input type="password" class="form-control" name="password">
                       </div>

                       <div class="form-group">
                           <button type="submit" class="btn btn-success">login</button>
                       </div>
                       <div>
                           <p>Not Registered? <a href="{% url 'fashionapp:register' %}">Register</a></p></div>
                   </form>

               </div>
           </div>
       </div>
   </div>
   </div>
 {% endblock %}

fashionapp/templates/fashionapp/register.html
{% extends 'fashionapp/base.html' %}
{%load crispy_forms_tags%}
{% block content %}
<div class="container-fluid">
    <div class="row">
         <div class="col-sm-4">
             <div class="panel panel-default">
                 <div class="panel-heading">
                     <h3 class="text-primary">Signup</h3>
                 </div>
                 <div class="panel-body">
                     <form method="post" action="" enctype="multipart/form-data">
                     {% csrf_token %}
                         {{form|crispy}}
                     <div class ="form-group">
                         <button type="submit" class="btn btn-success">submit</button>
                     </div>
                    <div>
                        <p>Already Registered? <a href="{% url 'fashionapp:login_user' %}">login</a></p></div>
                     </form>
                 </div>
             </div>
         </div>
</div>
</div>
{% endblock %}